/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UnitsImport } from './routes/units'
import { Route as TextImport } from './routes/text'
import { Route as TestsImport } from './routes/tests'
import { Route as FormImport } from './routes/form'
import { Route as ConstructorImport } from './routes/constructor'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const UnitsRoute = UnitsImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRoute,
} as any)

const TextRoute = TextImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => rootRoute,
} as any)

const TestsRoute = TestsImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRoute,
} as any)

const FormRoute = FormImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRoute,
} as any)

const ConstructorRoute = ConstructorImport.update({
  id: '/constructor',
  path: '/constructor',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/constructor': {
      id: '/constructor'
      path: '/constructor'
      fullPath: '/constructor'
      preLoaderRoute: typeof ConstructorImport
      parentRoute: typeof rootRoute
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormImport
      parentRoute: typeof rootRoute
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsImport
      parentRoute: typeof rootRoute
    }
    '/text': {
      id: '/text'
      path: '/text'
      fullPath: '/text'
      preLoaderRoute: typeof TextImport
      parentRoute: typeof rootRoute
    }
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/constructor': typeof ConstructorRoute
  '/form': typeof FormRoute
  '/tests': typeof TestsRoute
  '/text': typeof TextRoute
  '/units': typeof UnitsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/constructor': typeof ConstructorRoute
  '/form': typeof FormRoute
  '/tests': typeof TestsRoute
  '/text': typeof TextRoute
  '/units': typeof UnitsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/constructor': typeof ConstructorRoute
  '/form': typeof FormRoute
  '/tests': typeof TestsRoute
  '/text': typeof TextRoute
  '/units': typeof UnitsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/constructor' | '/form' | '/tests' | '/text' | '/units'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/constructor' | '/form' | '/tests' | '/text' | '/units'
  id:
    | '__root__'
    | '/'
    | '/constructor'
    | '/form'
    | '/tests'
    | '/text'
    | '/units'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConstructorRoute: typeof ConstructorRoute
  FormRoute: typeof FormRoute
  TestsRoute: typeof TestsRoute
  TextRoute: typeof TextRoute
  UnitsRoute: typeof UnitsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConstructorRoute: ConstructorRoute,
  FormRoute: FormRoute,
  TestsRoute: TestsRoute,
  TextRoute: TextRoute,
  UnitsRoute: UnitsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/constructor",
        "/form",
        "/tests",
        "/text",
        "/units"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/constructor": {
      "filePath": "constructor.tsx"
    },
    "/form": {
      "filePath": "form.tsx"
    },
    "/tests": {
      "filePath": "tests.tsx"
    },
    "/text": {
      "filePath": "text.tsx"
    },
    "/units": {
      "filePath": "units.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
