/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TextImport } from './routes/text'
import { Route as ConstructorImport } from './routes/constructor'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TextRoute = TextImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => rootRoute,
} as any)

const ConstructorRoute = ConstructorImport.update({
  id: '/constructor',
  path: '/constructor',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/constructor': {
      id: '/constructor'
      path: '/constructor'
      fullPath: '/constructor'
      preLoaderRoute: typeof ConstructorImport
      parentRoute: typeof rootRoute
    }
    '/text': {
      id: '/text'
      path: '/text'
      fullPath: '/text'
      preLoaderRoute: typeof TextImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/constructor': typeof ConstructorRoute
  '/text': typeof TextRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/constructor': typeof ConstructorRoute
  '/text': typeof TextRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/constructor': typeof ConstructorRoute
  '/text': typeof TextRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/constructor' | '/text'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/constructor' | '/text'
  id: '__root__' | '/' | '/constructor' | '/text'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConstructorRoute: typeof ConstructorRoute
  TextRoute: typeof TextRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConstructorRoute: ConstructorRoute,
  TextRoute: TextRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/constructor",
        "/text"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/constructor": {
      "filePath": "constructor.tsx"
    },
    "/text": {
      "filePath": "text.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
